In [1]:
import numpy as np

In [ ]:
print(np.__version__)

Nivel de dificultad: L1

P. Crea una matriz unidimensional de números del 0 al 9

In [60]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Nivel de dificultad: L1

P. Cree una matriz numpy de 3×3 de todos los valores True

In [ ]:
array2 = np.full([3,3],True,dtype=bool)
array2 

P. Extraer todos los números impares de arr

Aporte:

In [56]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
mask= (arr % 2 != 0)
print(arr[mask])

[1 3 5 7 9]


P. Reemplace todos los números impares por arr-1

In [59]:
arr[mask]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

P. Reemplace todos los números impares en arr con -1 sin cambiararr

In [63]:
out = np.where(array%2!=0,-1,array)
print(out)
array

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

P. Convertir una matriz 1D en una matriz 2D con 2 filas

In [66]:
array3 = array.reshape(2,-1)
array3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

P. Apilar matrices a y b verticalmente

In [68]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concat([a,b], axis=0)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

P. Apile las matrices a en b posición horizontal.

In [69]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concat([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

P. Cree el siguiente patrón sin codificarlo. Utilice únicamente funciones numpy y la siguiente matriz de entrada a

In [77]:
a = np.array([1,2,3])
array4 = np.repeat(a,3)
array5 = np.tile(a , 3)
array6 = np.concat([array4,array5], axis=0)
array6
 

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

P. Obtenga los elementos comunes entre a  y b

In [86]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [87]:
np.intersect1d(a,b)

array([2, 4])

P. De la matriz, a elimine todos los elementos presentes en la matriz. b

In [90]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
array7 = np.setdiff1d(b,a)
array7

array([6, 7, 8, 9])

In [94]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where (a==b)

(array([1, 3, 5, 7]),)